export const Questions = [
  {
    Q: "How many HTML files ReactJS use ?",
    optionA: "1",
    optionB: "2",
    optionC: "3",
    optionD: "4",
    answer: "A",
  },
  {
    Q: "What was ReactJS originally known as ?",
    optionA: "AngularJS",
    optionB: "SolidJS",
    optionC: "Preact",
    optionD: "FaxJS",
    answer: "D",
  },
  {
    Q: "Original creator of ReactJS ?",
    optionA: "Mark Zuckerberg",
    optionB: "Jordan Walke",
    optionC: "Paul Allen",
    optionD: "Chris Hughes",
    answer: "B",
  },
  {
    Q: "Which of the following is framework based on ReactJS ?",
    optionA: "vite",
    optionB: "NextJS",
    optionC: "VueJS",
    optionD: "ExpressJS",
    answer: "B",
  },
  {
    Q: "Which of the following is NOT a hook in ReactJS ?",
    optionA: "useLayoutEffect",
    optionB: "useId",
    optionC: "useRouteHandler",
    optionD: "useRouter",
    answer: "C",
  },
];